//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTiendita.ServicioProductos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        private double precioField;
        
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioProductos.ServicioProductoSoap")]
    public interface ServicioProductoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ProyectoTiendita.ServicioProductos.HelloWorldResponse HelloWorld(ProyectoTiendita.ServicioProductos.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.HelloWorldResponse> HelloWorldAsync(ProyectoTiendita.ServicioProductos.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerTodosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTodos", ReplyAction="*")]
        ProyectoTiendita.ServicioProductos.ObtenerTodosResponse ObtenerTodos(ProyectoTiendita.ServicioProductos.ObtenerTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ObtenerTodosResponse> ObtenerTodosAsync(ProyectoTiendita.ServicioProductos.ObtenerTodosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerUnoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUno", ReplyAction="*")]
        ProyectoTiendita.ServicioProductos.ObtenerUnoResponse ObtenerUno(ProyectoTiendita.ServicioProductos.ObtenerUnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUno", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ObtenerUnoResponse> ObtenerUnoAsync(ProyectoTiendita.ServicioProductos.ObtenerUnoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento prod del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProducto", ReplyAction="*")]
        ProyectoTiendita.ServicioProductos.AgregarProductoResponse AgregarProducto(ProyectoTiendita.ServicioProductos.AgregarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.AgregarProductoResponse> AgregarProductoAsync(ProyectoTiendita.ServicioProductos.AgregarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento prod del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarProducto", ReplyAction="*")]
        ProyectoTiendita.ServicioProductos.ModificarProductoResponse ModificarProducto(ProyectoTiendita.ServicioProductos.ModificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ModificarProductoResponse> ModificarProductoAsync(ProyectoTiendita.ServicioProductos.ModificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        bool EliminarProducto(int idProd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProd);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProyectoTiendita.ServicioProductos.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProyectoTiendita.ServicioProductos.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodos", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.ObtenerTodosRequestBody Body;
        
        public ObtenerTodosRequest() {
        }
        
        public ObtenerTodosRequest(ProyectoTiendita.ServicioProductos.ObtenerTodosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerTodosRequestBody {
        
        public ObtenerTodosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.ObtenerTodosResponseBody Body;
        
        public ObtenerTodosResponse() {
        }
        
        public ObtenerTodosResponse(ProyectoTiendita.ServicioProductos.ObtenerTodosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTodosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServicioProductos.Producto[] ObtenerTodosResult;
        
        public ObtenerTodosResponseBody() {
        }
        
        public ObtenerTodosResponseBody(ProyectoTiendita.ServicioProductos.Producto[] ObtenerTodosResult) {
            this.ObtenerTodosResult = ObtenerTodosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUno", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.ObtenerUnoRequestBody Body;
        
        public ObtenerUnoRequest() {
        }
        
        public ObtenerUnoRequest(ProyectoTiendita.ServicioProductos.ObtenerUnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProd;
        
        public ObtenerUnoRequestBody() {
        }
        
        public ObtenerUnoRequestBody(int idProd) {
            this.idProd = idProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.ObtenerUnoResponseBody Body;
        
        public ObtenerUnoResponse() {
        }
        
        public ObtenerUnoResponse(ProyectoTiendita.ServicioProductos.ObtenerUnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServicioProductos.Producto ObtenerUnoResult;
        
        public ObtenerUnoResponseBody() {
        }
        
        public ObtenerUnoResponseBody(ProyectoTiendita.ServicioProductos.Producto ObtenerUnoResult) {
            this.ObtenerUnoResult = ObtenerUnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProducto", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.AgregarProductoRequestBody Body;
        
        public AgregarProductoRequest() {
        }
        
        public AgregarProductoRequest(ProyectoTiendita.ServicioProductos.AgregarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServicioProductos.Producto prod;
        
        public AgregarProductoRequestBody() {
        }
        
        public AgregarProductoRequestBody(ProyectoTiendita.ServicioProductos.Producto prod) {
            this.prod = prod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.AgregarProductoResponseBody Body;
        
        public AgregarProductoResponse() {
        }
        
        public AgregarProductoResponse(ProyectoTiendita.ServicioProductos.AgregarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarProductoResult;
        
        public AgregarProductoResponseBody() {
        }
        
        public AgregarProductoResponseBody(bool AgregarProductoResult) {
            this.AgregarProductoResult = AgregarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarProducto", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.ModificarProductoRequestBody Body;
        
        public ModificarProductoRequest() {
        }
        
        public ModificarProductoRequest(ProyectoTiendita.ServicioProductos.ModificarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServicioProductos.Producto prod;
        
        public ModificarProductoRequestBody() {
        }
        
        public ModificarProductoRequestBody(ProyectoTiendita.ServicioProductos.Producto prod) {
            this.prod = prod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServicioProductos.ModificarProductoResponseBody Body;
        
        public ModificarProductoResponse() {
        }
        
        public ModificarProductoResponse(ProyectoTiendita.ServicioProductos.ModificarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModificarProductoResult;
        
        public ModificarProductoResponseBody() {
        }
        
        public ModificarProductoResponseBody(bool ModificarProductoResult) {
            this.ModificarProductoResult = ModificarProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioProductoSoapChannel : ProyectoTiendita.ServicioProductos.ServicioProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProductoSoapClient : System.ServiceModel.ClientBase<ProyectoTiendita.ServicioProductos.ServicioProductoSoap>, ProyectoTiendita.ServicioProductos.ServicioProductoSoap {
        
        public ServicioProductoSoapClient() {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServicioProductos.HelloWorldResponse ProyectoTiendita.ServicioProductos.ServicioProductoSoap.HelloWorld(ProyectoTiendita.ServicioProductos.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProyectoTiendita.ServicioProductos.HelloWorldRequest inValue = new ProyectoTiendita.ServicioProductos.HelloWorldRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.HelloWorldRequestBody();
            ProyectoTiendita.ServicioProductos.HelloWorldResponse retVal = ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.HelloWorldResponse> ProyectoTiendita.ServicioProductos.ServicioProductoSoap.HelloWorldAsync(ProyectoTiendita.ServicioProductos.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.HelloWorldResponse> HelloWorldAsync() {
            ProyectoTiendita.ServicioProductos.HelloWorldRequest inValue = new ProyectoTiendita.ServicioProductos.HelloWorldRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.HelloWorldRequestBody();
            return ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServicioProductos.ObtenerTodosResponse ProyectoTiendita.ServicioProductos.ServicioProductoSoap.ObtenerTodos(ProyectoTiendita.ServicioProductos.ObtenerTodosRequest request) {
            return base.Channel.ObtenerTodos(request);
        }
        
        public ProyectoTiendita.ServicioProductos.Producto[] ObtenerTodos() {
            ProyectoTiendita.ServicioProductos.ObtenerTodosRequest inValue = new ProyectoTiendita.ServicioProductos.ObtenerTodosRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.ObtenerTodosRequestBody();
            ProyectoTiendita.ServicioProductos.ObtenerTodosResponse retVal = ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).ObtenerTodos(inValue);
            return retVal.Body.ObtenerTodosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ObtenerTodosResponse> ProyectoTiendita.ServicioProductos.ServicioProductoSoap.ObtenerTodosAsync(ProyectoTiendita.ServicioProductos.ObtenerTodosRequest request) {
            return base.Channel.ObtenerTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ObtenerTodosResponse> ObtenerTodosAsync() {
            ProyectoTiendita.ServicioProductos.ObtenerTodosRequest inValue = new ProyectoTiendita.ServicioProductos.ObtenerTodosRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.ObtenerTodosRequestBody();
            return ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).ObtenerTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServicioProductos.ObtenerUnoResponse ProyectoTiendita.ServicioProductos.ServicioProductoSoap.ObtenerUno(ProyectoTiendita.ServicioProductos.ObtenerUnoRequest request) {
            return base.Channel.ObtenerUno(request);
        }
        
        public ProyectoTiendita.ServicioProductos.Producto ObtenerUno(int idProd) {
            ProyectoTiendita.ServicioProductos.ObtenerUnoRequest inValue = new ProyectoTiendita.ServicioProductos.ObtenerUnoRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.ObtenerUnoRequestBody();
            inValue.Body.idProd = idProd;
            ProyectoTiendita.ServicioProductos.ObtenerUnoResponse retVal = ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).ObtenerUno(inValue);
            return retVal.Body.ObtenerUnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ObtenerUnoResponse> ProyectoTiendita.ServicioProductos.ServicioProductoSoap.ObtenerUnoAsync(ProyectoTiendita.ServicioProductos.ObtenerUnoRequest request) {
            return base.Channel.ObtenerUnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ObtenerUnoResponse> ObtenerUnoAsync(int idProd) {
            ProyectoTiendita.ServicioProductos.ObtenerUnoRequest inValue = new ProyectoTiendita.ServicioProductos.ObtenerUnoRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.ObtenerUnoRequestBody();
            inValue.Body.idProd = idProd;
            return ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).ObtenerUnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServicioProductos.AgregarProductoResponse ProyectoTiendita.ServicioProductos.ServicioProductoSoap.AgregarProducto(ProyectoTiendita.ServicioProductos.AgregarProductoRequest request) {
            return base.Channel.AgregarProducto(request);
        }
        
        public bool AgregarProducto(ProyectoTiendita.ServicioProductos.Producto prod) {
            ProyectoTiendita.ServicioProductos.AgregarProductoRequest inValue = new ProyectoTiendita.ServicioProductos.AgregarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.AgregarProductoRequestBody();
            inValue.Body.prod = prod;
            ProyectoTiendita.ServicioProductos.AgregarProductoResponse retVal = ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).AgregarProducto(inValue);
            return retVal.Body.AgregarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.AgregarProductoResponse> ProyectoTiendita.ServicioProductos.ServicioProductoSoap.AgregarProductoAsync(ProyectoTiendita.ServicioProductos.AgregarProductoRequest request) {
            return base.Channel.AgregarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.AgregarProductoResponse> AgregarProductoAsync(ProyectoTiendita.ServicioProductos.Producto prod) {
            ProyectoTiendita.ServicioProductos.AgregarProductoRequest inValue = new ProyectoTiendita.ServicioProductos.AgregarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.AgregarProductoRequestBody();
            inValue.Body.prod = prod;
            return ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).AgregarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServicioProductos.ModificarProductoResponse ProyectoTiendita.ServicioProductos.ServicioProductoSoap.ModificarProducto(ProyectoTiendita.ServicioProductos.ModificarProductoRequest request) {
            return base.Channel.ModificarProducto(request);
        }
        
        public bool ModificarProducto(ProyectoTiendita.ServicioProductos.Producto prod) {
            ProyectoTiendita.ServicioProductos.ModificarProductoRequest inValue = new ProyectoTiendita.ServicioProductos.ModificarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.ModificarProductoRequestBody();
            inValue.Body.prod = prod;
            ProyectoTiendita.ServicioProductos.ModificarProductoResponse retVal = ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).ModificarProducto(inValue);
            return retVal.Body.ModificarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ModificarProductoResponse> ProyectoTiendita.ServicioProductos.ServicioProductoSoap.ModificarProductoAsync(ProyectoTiendita.ServicioProductos.ModificarProductoRequest request) {
            return base.Channel.ModificarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServicioProductos.ModificarProductoResponse> ModificarProductoAsync(ProyectoTiendita.ServicioProductos.Producto prod) {
            ProyectoTiendita.ServicioProductos.ModificarProductoRequest inValue = new ProyectoTiendita.ServicioProductos.ModificarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServicioProductos.ModificarProductoRequestBody();
            inValue.Body.prod = prod;
            return ((ProyectoTiendita.ServicioProductos.ServicioProductoSoap)(this)).ModificarProductoAsync(inValue);
        }
        
        public bool EliminarProducto(int idProd) {
            return base.Channel.EliminarProducto(idProd);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProd) {
            return base.Channel.EliminarProductoAsync(idProd);
        }
    }
}
