CREATE DATABASE TIENDITA;
USE TIENDITA;
CREATE TABLE CLIENTES
(
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(60) NOT NULL,
DIRECCION VARCHAR(60) NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
EMAIL VARCHAR(60) PRIMARY KEY,
CONTRASENIA VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIOS
(

USUARIO VARCHAR(20) PRIMARY KEY,
CONTRASENIA VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDOS VARCHAR(60) NOT NULL,
TELEFONO VARCHAR(20) NOT NULL
);

CREATE TABLE PEDIDOS
(
NUM_PEDIDO INT auto_increment PRIMARY KEY,
EMAIL_CLIENTE VARCHAR(60) NOT NULL,
PRECIO_TOTAL DECIMAL(10,2) NOT NULL,
ESTADO_PEDIDO INT NOT NULL,
FECHA DATE NOT NULL,
HORA TIME NOT NULL,
CONSTRAINT FOREIGN KEY (EMAIL_CLIENTE) REFERENCES CLIENTES(EMAIL)
);

CREATE TABLE PRODUCTOS
(
ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(40) NOT NULL,
PRECIO DECIMAL(10,2) NOT NULL,
ESTADO INT NOT NULL
);

CREATE TABLE DETALLE_DE_PEDIDOS
(
NUM_PEDIDO INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
CANTIDAD INT NOT NULL,
PRIMARY KEY(NUM_PEDIDO,ID_PRODUCTO),
CONSTRAINT FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDOS(NUM_PEDIDO),
CONSTRAINT FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);