//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTiendita.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        private double precioField;
        
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SevicioProductosSoap")]
    public interface SevicioProductosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ProyectoTiendita.ServiceReference1.HelloWorldResponse HelloWorld(ProyectoTiendita.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ProyectoTiendita.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerTodosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTodos", ReplyAction="*")]
        ProyectoTiendita.ServiceReference1.ObtenerTodosResponse ObtenerTodos(ProyectoTiendita.ServiceReference1.ObtenerTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ObtenerTodosResponse> ObtenerTodosAsync(ProyectoTiendita.ServiceReference1.ObtenerTodosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerUnoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUno", ReplyAction="*")]
        ProyectoTiendita.ServiceReference1.ObtenerUnoResponse ObtenerUno(ProyectoTiendita.ServiceReference1.ObtenerUnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUno", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ObtenerUnoResponse> ObtenerUnoAsync(ProyectoTiendita.ServiceReference1.ObtenerUnoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento prod del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProducto", ReplyAction="*")]
        ProyectoTiendita.ServiceReference1.AgregarProductoResponse AgregarProducto(ProyectoTiendita.ServiceReference1.AgregarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.AgregarProductoResponse> AgregarProductoAsync(ProyectoTiendita.ServiceReference1.AgregarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento prod del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarProducto", ReplyAction="*")]
        ProyectoTiendita.ServiceReference1.ModificarProductoResponse ModificarProducto(ProyectoTiendita.ServiceReference1.ModificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ModificarProductoResponse> ModificarProductoAsync(ProyectoTiendita.ServiceReference1.ModificarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        bool EliminarProducto(int idProd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProd);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ProyectoTiendita.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ProyectoTiendita.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodos", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.ObtenerTodosRequestBody Body;
        
        public ObtenerTodosRequest() {
        }
        
        public ObtenerTodosRequest(ProyectoTiendita.ServiceReference1.ObtenerTodosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerTodosRequestBody {
        
        public ObtenerTodosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTodosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.ObtenerTodosResponseBody Body;
        
        public ObtenerTodosResponse() {
        }
        
        public ObtenerTodosResponse(ProyectoTiendita.ServiceReference1.ObtenerTodosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerTodosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServiceReference1.Producto[] ObtenerTodosResult;
        
        public ObtenerTodosResponseBody() {
        }
        
        public ObtenerTodosResponseBody(ProyectoTiendita.ServiceReference1.Producto[] ObtenerTodosResult) {
            this.ObtenerTodosResult = ObtenerTodosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUno", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.ObtenerUnoRequestBody Body;
        
        public ObtenerUnoRequest() {
        }
        
        public ObtenerUnoRequest(ProyectoTiendita.ServiceReference1.ObtenerUnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProd;
        
        public ObtenerUnoRequestBody() {
        }
        
        public ObtenerUnoRequestBody(int idProd) {
            this.idProd = idProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.ObtenerUnoResponseBody Body;
        
        public ObtenerUnoResponse() {
        }
        
        public ObtenerUnoResponse(ProyectoTiendita.ServiceReference1.ObtenerUnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServiceReference1.Producto ObtenerUnoResult;
        
        public ObtenerUnoResponseBody() {
        }
        
        public ObtenerUnoResponseBody(ProyectoTiendita.ServiceReference1.Producto ObtenerUnoResult) {
            this.ObtenerUnoResult = ObtenerUnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProducto", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.AgregarProductoRequestBody Body;
        
        public AgregarProductoRequest() {
        }
        
        public AgregarProductoRequest(ProyectoTiendita.ServiceReference1.AgregarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServiceReference1.Producto prod;
        
        public AgregarProductoRequestBody() {
        }
        
        public AgregarProductoRequestBody(ProyectoTiendita.ServiceReference1.Producto prod) {
            this.prod = prod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.AgregarProductoResponseBody Body;
        
        public AgregarProductoResponse() {
        }
        
        public AgregarProductoResponse(ProyectoTiendita.ServiceReference1.AgregarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarProductoResult;
        
        public AgregarProductoResponseBody() {
        }
        
        public AgregarProductoResponseBody(bool AgregarProductoResult) {
            this.AgregarProductoResult = AgregarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarProducto", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.ModificarProductoRequestBody Body;
        
        public ModificarProductoRequest() {
        }
        
        public ModificarProductoRequest(ProyectoTiendita.ServiceReference1.ModificarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectoTiendita.ServiceReference1.Producto prod;
        
        public ModificarProductoRequestBody() {
        }
        
        public ModificarProductoRequestBody(ProyectoTiendita.ServiceReference1.Producto prod) {
            this.prod = prod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectoTiendita.ServiceReference1.ModificarProductoResponseBody Body;
        
        public ModificarProductoResponse() {
        }
        
        public ModificarProductoResponse(ProyectoTiendita.ServiceReference1.ModificarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModificarProductoResult;
        
        public ModificarProductoResponseBody() {
        }
        
        public ModificarProductoResponseBody(bool ModificarProductoResult) {
            this.ModificarProductoResult = ModificarProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SevicioProductosSoapChannel : ProyectoTiendita.ServiceReference1.SevicioProductosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SevicioProductosSoapClient : System.ServiceModel.ClientBase<ProyectoTiendita.ServiceReference1.SevicioProductosSoap>, ProyectoTiendita.ServiceReference1.SevicioProductosSoap {
        
        public SevicioProductosSoapClient() {
        }
        
        public SevicioProductosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SevicioProductosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SevicioProductosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SevicioProductosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServiceReference1.HelloWorldResponse ProyectoTiendita.ServiceReference1.SevicioProductosSoap.HelloWorld(ProyectoTiendita.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ProyectoTiendita.ServiceReference1.HelloWorldRequest inValue = new ProyectoTiendita.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.HelloWorldRequestBody();
            ProyectoTiendita.ServiceReference1.HelloWorldResponse retVal = ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.HelloWorldResponse> ProyectoTiendita.ServiceReference1.SevicioProductosSoap.HelloWorldAsync(ProyectoTiendita.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ProyectoTiendita.ServiceReference1.HelloWorldRequest inValue = new ProyectoTiendita.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.HelloWorldRequestBody();
            return ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServiceReference1.ObtenerTodosResponse ProyectoTiendita.ServiceReference1.SevicioProductosSoap.ObtenerTodos(ProyectoTiendita.ServiceReference1.ObtenerTodosRequest request) {
            return base.Channel.ObtenerTodos(request);
        }
        
        public ProyectoTiendita.ServiceReference1.Producto[] ObtenerTodos() {
            ProyectoTiendita.ServiceReference1.ObtenerTodosRequest inValue = new ProyectoTiendita.ServiceReference1.ObtenerTodosRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.ObtenerTodosRequestBody();
            ProyectoTiendita.ServiceReference1.ObtenerTodosResponse retVal = ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).ObtenerTodos(inValue);
            return retVal.Body.ObtenerTodosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ObtenerTodosResponse> ProyectoTiendita.ServiceReference1.SevicioProductosSoap.ObtenerTodosAsync(ProyectoTiendita.ServiceReference1.ObtenerTodosRequest request) {
            return base.Channel.ObtenerTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ObtenerTodosResponse> ObtenerTodosAsync() {
            ProyectoTiendita.ServiceReference1.ObtenerTodosRequest inValue = new ProyectoTiendita.ServiceReference1.ObtenerTodosRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.ObtenerTodosRequestBody();
            return ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).ObtenerTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServiceReference1.ObtenerUnoResponse ProyectoTiendita.ServiceReference1.SevicioProductosSoap.ObtenerUno(ProyectoTiendita.ServiceReference1.ObtenerUnoRequest request) {
            return base.Channel.ObtenerUno(request);
        }
        
        public ProyectoTiendita.ServiceReference1.Producto ObtenerUno(int idProd) {
            ProyectoTiendita.ServiceReference1.ObtenerUnoRequest inValue = new ProyectoTiendita.ServiceReference1.ObtenerUnoRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.ObtenerUnoRequestBody();
            inValue.Body.idProd = idProd;
            ProyectoTiendita.ServiceReference1.ObtenerUnoResponse retVal = ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).ObtenerUno(inValue);
            return retVal.Body.ObtenerUnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ObtenerUnoResponse> ProyectoTiendita.ServiceReference1.SevicioProductosSoap.ObtenerUnoAsync(ProyectoTiendita.ServiceReference1.ObtenerUnoRequest request) {
            return base.Channel.ObtenerUnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ObtenerUnoResponse> ObtenerUnoAsync(int idProd) {
            ProyectoTiendita.ServiceReference1.ObtenerUnoRequest inValue = new ProyectoTiendita.ServiceReference1.ObtenerUnoRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.ObtenerUnoRequestBody();
            inValue.Body.idProd = idProd;
            return ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).ObtenerUnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServiceReference1.AgregarProductoResponse ProyectoTiendita.ServiceReference1.SevicioProductosSoap.AgregarProducto(ProyectoTiendita.ServiceReference1.AgregarProductoRequest request) {
            return base.Channel.AgregarProducto(request);
        }
        
        public bool AgregarProducto(ProyectoTiendita.ServiceReference1.Producto prod) {
            ProyectoTiendita.ServiceReference1.AgregarProductoRequest inValue = new ProyectoTiendita.ServiceReference1.AgregarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.AgregarProductoRequestBody();
            inValue.Body.prod = prod;
            ProyectoTiendita.ServiceReference1.AgregarProductoResponse retVal = ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).AgregarProducto(inValue);
            return retVal.Body.AgregarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.AgregarProductoResponse> ProyectoTiendita.ServiceReference1.SevicioProductosSoap.AgregarProductoAsync(ProyectoTiendita.ServiceReference1.AgregarProductoRequest request) {
            return base.Channel.AgregarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.AgregarProductoResponse> AgregarProductoAsync(ProyectoTiendita.ServiceReference1.Producto prod) {
            ProyectoTiendita.ServiceReference1.AgregarProductoRequest inValue = new ProyectoTiendita.ServiceReference1.AgregarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.AgregarProductoRequestBody();
            inValue.Body.prod = prod;
            return ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).AgregarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoTiendita.ServiceReference1.ModificarProductoResponse ProyectoTiendita.ServiceReference1.SevicioProductosSoap.ModificarProducto(ProyectoTiendita.ServiceReference1.ModificarProductoRequest request) {
            return base.Channel.ModificarProducto(request);
        }
        
        public bool ModificarProducto(ProyectoTiendita.ServiceReference1.Producto prod) {
            ProyectoTiendita.ServiceReference1.ModificarProductoRequest inValue = new ProyectoTiendita.ServiceReference1.ModificarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.ModificarProductoRequestBody();
            inValue.Body.prod = prod;
            ProyectoTiendita.ServiceReference1.ModificarProductoResponse retVal = ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).ModificarProducto(inValue);
            return retVal.Body.ModificarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ModificarProductoResponse> ProyectoTiendita.ServiceReference1.SevicioProductosSoap.ModificarProductoAsync(ProyectoTiendita.ServiceReference1.ModificarProductoRequest request) {
            return base.Channel.ModificarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoTiendita.ServiceReference1.ModificarProductoResponse> ModificarProductoAsync(ProyectoTiendita.ServiceReference1.Producto prod) {
            ProyectoTiendita.ServiceReference1.ModificarProductoRequest inValue = new ProyectoTiendita.ServiceReference1.ModificarProductoRequest();
            inValue.Body = new ProyectoTiendita.ServiceReference1.ModificarProductoRequestBody();
            inValue.Body.prod = prod;
            return ((ProyectoTiendita.ServiceReference1.SevicioProductosSoap)(this)).ModificarProductoAsync(inValue);
        }
        
        public bool EliminarProducto(int idProd) {
            return base.Channel.EliminarProducto(idProd);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int idProd) {
            return base.Channel.EliminarProductoAsync(idProd);
        }
    }
}
